### ISSUE TITLE
ToDo Features

### ISSUE THREAD

**Issue by mastercion** [mastercion/minecraft_mod_fabric_blockowner#1]
### Features that might get added in some of the next releases

- [x]  Also track&display placed Block Date
- [ ]  Assign already placed blocks to Player
- [x] Silence Debug info in Console using a Command 
- [x] Change Selection tool using a command
- [x] Customize message formating
- [x] Display Gamemode If needed
- [ ] Also track non Hand placed Blocks
- [ ] Info like 3Days 2hrs 15m ago etc
- [x] Also add Dimension Tag to BlockData
> By Requests https://github.com/mastercion/minecraft_mod_fabric_blockowner/issues/8#issue-2428422649
- [x] Output Block History in Chat
- [ ] Make Titel Message Optional
- [ ] Add Mod Menu support
- [ ] View Blocks by Players who are offline (Visual&BlockList command)
- [ ] Add Placement Type (Hand, Command, Fallen, by Block, etc.)

**Comment by PiggoRBLX** [comment]
Hiya, I cannot for the life of me find out how to use the tool to click on blocks and have it reveal who placed them. Would you be able to explain how?

**Comment by mastercion** [comment]
> Hiya, I cannot for the life of me find out how to use the tool to click on blocks and have it reveal who placed them. Would you be able to explain how?

Hey, thanks for your interest in my mod, BlockOwner!

I kindly ask you to open a new issue using the Bug format and provide all the necessary information as outlined in the template. Without those details, I won't be able to assist you further.

I'll be locking this conversation since it wasn't intended for this purpose. Creating a separate issue will also help future users with the same problem easily find your post along with any related solutions.

Thanks for your understanding!

**Comment by PiggoRBLX** [comment]
Well, it's not quite a bug. I just don't know what button to click in order
to check who placed a certain block. I have the tool set to a stone hoe,
does any stone hoe work? If so, what button do I click to use it?

**Comment by mastercion** [comment]
> Well, it's not quite a bug. I just don't know what button to click in order
> to check who placed a certain block. I have the tool set to a stone hoe,
> does any stone hoe work? If so, what button do I click to use it?
> […](#)

I suggest reading the Features tab on the Mod Overview page to understand how this mod works. Please note that this mod requires Operator permissions.

As mentioned earlier, I will be closing this conversation.

Thanks for your understanding!
